# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\stranger\Desktop\RoDe.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RoDe(object):
    def setupUi(self, RoDe):
        RoDe.setObjectName("RoDe")
        RoDe.resize(800, 624)
        RoDe.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(RoDe)
        self.centralwidget.setObjectName("centralwidget")
        self.Fkin = QtWidgets.QPushButton(self.centralwidget)
        self.Fkin.setGeometry(QtCore.QRect(20, 230, 93, 28))
        self.Fkin.setObjectName("Fkin")
        self.Ikin = QtWidgets.QPushButton(self.centralwidget)
        self.Ikin.setGeometry(QtCore.QRect(510, 180, 93, 28))
        self.Ikin.setObjectName("Ikin")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(20, 400, 151, 131))
        self.tableView.setObjectName("tableView")
        self.actro = QtWidgets.QCheckBox(self.centralwidget)
        self.actro.setGeometry(QtCore.QRect(20, 20, 141, 20))
        self.actro.setObjectName("actro")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(330, 50, 161, 111))
        self.listView.setObjectName("listView")
        self.listView_2 = QtWidgets.QListView(self.centralwidget)
        self.listView_2.setGeometry(QtCore.QRect(610, 50, 161, 111))
        self.listView_2.setObjectName("listView_2")
        self.listView_3 = QtWidgets.QListView(self.centralwidget)
        self.listView_3.setGeometry(QtCore.QRect(330, 270, 171, 121))
        self.listView_3.setObjectName("listView_3")
        self.listView_4 = QtWidgets.QListView(self.centralwidget)
        self.listView_4.setGeometry(QtCore.QRect(610, 270, 171, 111))
        self.listView_4.setObjectName("listView_4")
        self.l1 = QtWidgets.QLineEdit(self.centralwidget)
        self.l1.setGeometry(QtCore.QRect(80, 90, 113, 22))
        self.l1.setObjectName("l1")
        self.l2 = QtWidgets.QLineEdit(self.centralwidget)
        self.l2.setGeometry(QtCore.QRect(80, 130, 113, 22))
        self.l2.setObjectName("l2")
        self.l3 = QtWidgets.QLineEdit(self.centralwidget)
        self.l3.setGeometry(QtCore.QRect(80, 170, 113, 22))
        self.l3.setObjectName("l3")
        self.AIkin = QtWidgets.QCheckBox(self.centralwidget)
        self.AIkin.setGeometry(QtCore.QRect(490, 400, 131, 20))
        self.AIkin.setObjectName("AIkin")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 60, 171, 16))
        self.label_4.setObjectName("label_4")
        self.L1 = QtWidgets.QLabel(self.centralwidget)
        self.L1.setGeometry(QtCore.QRect(20, 90, 41, 21))
        self.L1.setObjectName("L1")
        self.L2 = QtWidgets.QLabel(self.centralwidget)
        self.L2.setGeometry(QtCore.QRect(20, 130, 41, 20))
        self.L2.setObjectName("L2")
        self.L3 = QtWidgets.QLabel(self.centralwidget)
        self.L3.setGeometry(QtCore.QRect(20, 170, 41, 16))
        self.L3.setObjectName("L3")
        self.th1 = QtWidgets.QLineEdit(self.centralwidget)
        self.th1.setGeometry(QtCore.QRect(80, 270, 113, 22))
        self.th1.setObjectName("th1")
        self.th2 = QtWidgets.QLineEdit(self.centralwidget)
        self.th2.setGeometry(QtCore.QRect(80, 310, 113, 22))
        self.th2.setObjectName("th2")
        self.th3 = QtWidgets.QLineEdit(self.centralwidget)
        self.th3.setGeometry(QtCore.QRect(80, 350, 113, 22))
        self.th3.setObjectName("th3")
        self.fth1 = QtWidgets.QLabel(self.centralwidget)
        self.fth1.setGeometry(QtCore.QRect(20, 270, 55, 16))
        self.fth1.setObjectName("fth1")
        self.fth3 = QtWidgets.QLabel(self.centralwidget)
        self.fth3.setGeometry(QtCore.QRect(20, 350, 55, 16))
        self.fth3.setObjectName("fth3")
        self.px = QtWidgets.QLineEdit(self.centralwidget)
        self.px.setGeometry(QtCore.QRect(350, 220, 113, 22))
        self.px.setObjectName("px")
        self.py = QtWidgets.QLineEdit(self.centralwidget)
        self.py.setGeometry(QtCore.QRect(500, 220, 113, 22))
        self.py.setObjectName("py")
        self.pz = QtWidgets.QLineEdit(self.centralwidget)
        self.pz.setGeometry(QtCore.QRect(650, 220, 113, 22))
        self.pz.setObjectName("pz")
        self.fth2 = QtWidgets.QLabel(self.centralwidget)
        self.fth2.setGeometry(QtCore.QRect(20, 310, 55, 16))
        self.fth2.setObjectName("fth2")
        self.ex = QtWidgets.QLabel(self.centralwidget)
        self.ex.setGeometry(QtCore.QRect(324, 220, 21, 20))
        self.ex.setObjectName("ex")
        self.ey = QtWidgets.QLabel(self.centralwidget)
        self.ey.setGeometry(QtCore.QRect(480, 220, 20, 20))
        self.ey.setObjectName("ey")
        self.ez = QtWidgets.QLabel(self.centralwidget)
        self.ez.setGeometry(QtCore.QRect(630, 220, 20, 20))
        self.ez.setObjectName("ez")
        self.Fdyn = QtWidgets.QPushButton(self.centralwidget)
        self.Fdyn.setGeometry(QtCore.QRect(360, 460, 93, 28))
        self.Fdyn.setObjectName("Fdyn")
        self.Idyn = QtWidgets.QPushButton(self.centralwidget)
        self.Idyn.setGeometry(QtCore.QRect(640, 460, 93, 28))
        self.Idyn.setObjectName("Idyn")
        RoDe.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RoDe)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        RoDe.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RoDe)
        self.statusbar.setObjectName("statusbar")
        RoDe.setStatusBar(self.statusbar)

        self.retranslateUi(RoDe)
        QtCore.QMetaObject.connectSlotsByName(RoDe)

    def retranslateUi(self, RoDe):
        _translate = QtCore.QCoreApplication.translate
        RoDe.setWindowTitle(_translate("RoDe", "RoDe"))
        self.Fkin.setText(_translate("RoDe", "Fkin"))
        self.Ikin.setText(_translate("RoDe", "Ikin"))
        self.actro.setText(_translate("RoDe", "3R Articulated  Arm"))
        self.AIkin.setText(_translate("RoDe", "Control Manually"))
        self.label_4.setText(_translate("RoDe", "Enter the length of the links"))
        self.L1.setText(_translate("RoDe", "LINK1"))
        self.L2.setText(_translate("RoDe", "LINK2"))
        self.L3.setText(_translate("RoDe", "LINK3"))
        self.fth1.setText(_translate("RoDe", "Angle1"))
        self.fth3.setText(_translate("RoDe", "Angle3"))
        self.fth2.setText(_translate("RoDe", "Angle2"))
        self.ex.setText(_translate("RoDe", "ex"))
        self.ey.setText(_translate("RoDe", "ey"))
        self.ez.setText(_translate("RoDe", "ez"))
        self.Fdyn.setText(_translate("RoDe", "Fdyn"))
        self.Idyn.setText(_translate("RoDe", "Idyn"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RoDe = QtWidgets.QMainWindow()
    ui = Ui_RoDe()
    ui.setupUi(RoDe)
    RoDe.show()
    sys.exit(app.exec_())

